onflow/flow-playground-api

- go.mod
- go.sum
Missing entry in `go.sum` causing build to fail. Missing because of a bad merge.
> Add missing dep. Fixes Docker build.

- CODEOWNERS
I think adding me as a code owner is needed so I can do code reviews for new developers.
> Add sideninja as code owner

- server/config/config.go
- server/server.go
Refactor configuration to a single global instance.
______
> Refactor config to global

- blockchain/projects.go
- controller/accounts.go
- resolver.go
- server/server.go
- telemetry/logger.go
This is temp telemetry to debug staging, this should be reverted and proper telemetry solution should be added later.
______
> Debug Telemetry

- adapter/models.go
- auth/auth.go
- blockchain/cache.go
- blockchain/emulator.go
- blockchain/projects.go
- controller/accounts.go
- resolver.go
- server/server.go
- telemetry/logger.go
- telemetry/runtimeLogger.go
Added runtime calculations for debugging purposes.
______
> Add runtime calculation logging

- blockchain/cache.go
- blockchain/emulator.go
- blockchain/projects.go
- resolver.go
> add better telemtry

- resolver.go
> Cleanup code

- .gitignore
- adapter/state.go
- blockchain/projects_test.go
- controller/accounts.go
- migrate/migrate_test.go
- model/account.go
- model/error.go
- model/project.go
- model/script.go
- model/transaction.go
- playground_test.go
- resolver.go
- storage/sql.go
General code improvements and some regression fixes.
______
> Test bugfixes

- .gitignore
- adapter/state.go
- blockchain/cache.go
- blockchain/cache_test.go
- blockchain/mutex.go
- blockchain/mutex_test.go
- blockchain/projects.go
- blockchain/projects_test.go
- controller/accounts.go
- controller/projects.go
- migrate/migrate_test.go
- model/account.go
- model/error.go
- model/project.go
- model/script.go
- model/transaction.go
- playground_test.go
- resolver.go
- storage/sql.go
Closes: #69 
Refactor mutex to use a controlled lock and also refactor cache with added tests for both. 
______
> Cache invalidation and mutex improvements

- .github/workflows/ci.yml
- blockchain/cache_test.go
- blockchain/emulator_test.go
- blockchain/projects_test.go
- controller/projects_test.go
Closes: #51 
- Fixed lintier issues along with the Github action
- Added CI to staging
______
> Fix linter

- blockchain/projects_test.go
- controller/projects_test.go
- migrate/migrate_test.go
- playground_test.go
Enabled test cases to run in parallel to speed up CI testing.
______
> Parallelize test cases

- storage/sql.go
Sorting of templates by index.
______
> Order templates by index

- blockchain/projects_test.go
- controller/projects_test.go
- migrate/migrate_test.go
- playground_test.go
Reverts onflow/flow-playground-api#84
> Revert "Parallelize test cases"

- controller/projects.go
- e2eTest/constants.go
- e2eTest/project_test.go
- generated.go
- model/project.go
- resolver.go
- schema.graphql
- storage/sql.go
Closes: #111 
Enable the FE to see the updated at time for projects
- Added updatedAt to project schema
- Created resolver to format updated at time
- Added project e2e test for updated at time
______
> Expose project UpdatedAt time

- controller/files.go
- e2eTest/project_test.go
Closes: #126 
- Adding, updating, or deleting files will now also update the project in order to set the new updated_at time.
______
> File changes update project updated_at

- controller/embeds_test.go
- go.mod
Remove not needed test library as we already use testify
______
> Remove unused test package

- controller/files.go
- storage/sql.go
- storage/storage.go
Closes: #145 
- Fixed project deletion logic to include deletion of files and executions
- Cleaned up fileChanged code
______
> Update project deletion logic

- middleware/errors/errors.go
Added error extensions inside the error itself so the FE can access them easily.
______
> Add extensions to errors

- server/config/platform.go
Set up v2 open beta:
- Added platform type for open beta
______
> Set up v2 open beta

- go.mod
- go.sum
Closes: #162 
- Updates flow-emulator to v0.42.0
______
> Update flow emulator for v2

- server/config/telemetry.go
- server/server.go
- storage/sql.go
- storage/storage.go
- telemetry/metrics.go
- telemetry/projects.go
Closes: #177 
Added metrics to count the total number of projects in the database
______
> Add total project metrics

- .github/dependabot.yml
Closes: #178 
Added dependabot targeting v2 branch
______
> Dependabot v2 branch
